#!/usr/bin/env python3
"""Encode the prepped portrait as a compact brightness grid for <BinaryPortrait>.

Input is the graded, background-free portrait produced by the profile-forge
pipeline (github.com/buildwithsabba/profile-forge, scripts/prep_photo.py).
Output is lib/portrait-data.ts: one digit 0-9 per cell, row-major, so the
whole face ships as a ~6 KB string instead of an image.

    python3 scripts/make_binary_portrait.py path/to/source-prepped.png
"""
import sys

import numpy as np
from PIL import Image

SRC = sys.argv[1] if len(sys.argv) > 1 else \
    "../buildwithsabba/assets/source-prepped.png"
OUT = "lib/portrait-data.ts"
COLS = 76
CELL_ASPECT = 0.62          # glyph width / line height in the canvas renderer

img = Image.open(SRC).convert("L")
w, h = img.size
rows = round(COLS * (h / w) * CELL_ASPECT)
grid = np.asarray(img.resize((COLS, rows), Image.LANCZOS), dtype=np.float32) / 255
levels = np.clip((grid * 9).round().astype(int), 0, 9)

# Trim rows and columns with no ink (the renderer skips levels < 2), keeping
# a small margin, so the face fills its panel instead of floating in it.
MARGIN = 1
ink = levels >= 2
r = np.where(ink.any(axis=1))[0]
c = np.where(ink.sum(axis=0) > 1)[0]
levels = levels[max(0, r[0] - MARGIN):r[-1] + 1 + MARGIN,
                max(0, c[0] - MARGIN):c[-1] + 1 + MARGIN]
rows, COLS = levels.shape
data = "".join("".join(str(v) for v in row) for row in levels)

with open(OUT, "w") as f:
    f.write(f"""// Generated by scripts/make_binary_portrait.py — do not edit by hand.
// Brightness grid of the portrait: one digit 0-9 per cell, row-major.
export const PORTRAIT = {{
    cols: {COLS},
    rows: {rows},
    data: "{data}",
}} as const;
""")
print(f"wrote {OUT}  {COLS}x{rows}  {len(data)} cells  "
      f"ink {(levels > 1).mean():.0%}")
